accounts/urls.py
from django.urls import path, include, reverse
from django.contrib import admin
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('login/', auth_views.LoginView.as_view(), name="login"),
    path('index/', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_view, name='logout'),
]

todoapp/urls.py
from django.urls import path
from . import views

app_name = 'todoapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('addtask/', views.add_task, name='add_task'),
    path('removetask/<int:task_id>', views.remove_task, name='remove_task'),
]

todosite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='accounts/login/')),
    path('admin/', admin.site.urls),
    path('todoapp/', include('todoapp.urls')),
    path('accounts/', include('accounts.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

todoapp/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Task(models.Model):
    task_text = models.CharField(max_length=120)
    task_deadline = models.DateTimeField()
    add_time = models.DateTimeField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return self.task_text

todoapp/forms.py
from django import forms
from django.utils.datetime_safe import datetime
from django.utils.timezone import now


class TaskAddForm(forms.Form):
    task_text = forms.CharField(max_length=30)
    task_deadline = forms.DateTimeField()
    add_time = forms.DateTimeField()

    def clean(self):
        cleaned_data = super().clean()
        deadline = cleaned_data.get("task_deadline")
        addtime = cleaned_data.get("add_time")
        if deadline and addtime:
            if deadline < addtime:
                raise forms.ValidationError("Deadline should not be in past or before add time")

accounts/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from django.urls import reverse


def index(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('todoapp:index'))
        else:
            return HttpResponseRedirect(reverse('accounts:login'))
    else:
        return render(request, 'registration/login.html')


def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('accounts:login'))
    else:
        form = UserCreationForm()
    context = {'form': form}

    return render(request, 'accounts/register.html', context)


def logout_view(request):
    logout(request)

todoapp/views.py
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .models import Task
from .forms import TaskAddForm


# Create your views here.
def index(request):
    # change is yet to make
    pk = request.user.id
    user = User.objects.get(pk=pk)
    task_list = Task.objects.filter(user=user).order_by('task_deadline', 'task_text')
    context = {'task_list': task_list}
    return render(request, 'todoapp/index.html', context)


def add_task(request):
    if not request.user.is_authenticated:
        HttpResponseRedirect(reverse('accounts:login'))
    if request.method == 'POST':
        form = TaskAddForm(request.POST)

        if form.is_valid():
            task = Task()
            task.task_text = form.cleaned_data.get('task_text')
            task.add_time = form.cleaned_data.get('add_time')
            task.task_deadline = form.cleaned_data.get('task_deadline')
            task.user = request.user
            task.save()
            return HttpResponseRedirect(reverse('todoapp:index'))
        return render(request, 'todoapp/addtask.html', {'form': form})
    else:
        form = TaskAddForm()
        context = {'form': form}
        return render(request, 'todoapp/addtask.html', context)


def remove_task(request, task_id):
    Task.objects.get(pk=task_id).delete()
    return HttpResponseRedirect(reverse('todoapp:index'))

accounts/templates/accounts/base.html
{% load static%}
<link rel="stylesheet" type="text/css" href="{% static 'accounts/css/bootstrap.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'accounts/css/bootstrap-reboot.css' %}">
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Title {% endblock title%}</title>
</head>
<body>
    <div class="authentication">
        <div class="home"><a href="{% url 'todoapp:index'%}">Home</a></div>
        {% if user.is_authenticated %}
            <a href="{% url 'accounts:logout' %}">Logout</a>
        {% else %}
            <div class="login signup">
                <a href="{% url 'accounts:register' %}">Signup</a>
                <a href="{% url 'accounts:login' %}">Login</a>
            </div>
        {%endif %}
    </div>
    {% block content %}
        Content
    {% endblock content %}
</body>
</html>

accounts/templates/accounts/register.html
{% extends 'accounts/base.html' %}
{% block title %}
    Register
{% endblock%}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col"></div>
            <div class="col-6">
                <div class="container">
                    <form method="post" action="{% url 'accounts:register'%}">
                        {%csrf_token%}
                        {{ form.non_field_errors }}
                        {% for field in form %}
                            <div class="row">
                                {{field.errors}}
                            </div>
                            <div class="row">
                                <div class="col">
                                    {{field.label_tag}}
                                </div>
                                <div class="col">
                                    {{field}}
                                </div>
                            </div>
                        {% endfor%}
                        <div class="row">
                            <input class="btn btn-primary" type="submit" value="Sign Up">
                        </div>
                    </form>
                </div>
            </div>
            <div class="col"></div>
        </div>
    </div>
{% endblock content%}

todoapp/templates/todoapp/addtask.html
{% extends 'todoapp/base.html' %}

{% block title %}
    Add task
{% endblock title%}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col"></div>
            <div class="col-6">
                <div class="container">
                    <form method="post" >
                        {%csrf_token%}
                        {{ form.non_field_errors }}
                        {% for field in form %}
                            <div class="row">
                                {{field.errors}}
                            </div>
                            <div class="row">
                                <div class="col">
                                    {{field.label_tag}}
                                </div>
                                <div class="col">
                                    {{field}}
                                </div>
                            </div>
                        {% endfor%}
                        <div class="row">
                            <input class="btn btn-primary" type="submit" value="Submit">
                        </div>
                    </form>
                </div>
            </div>
            <div class="col"></div>
        </div>
    </div>
{% endblock content%}

todoapp/templates/todoapp/base.html
{% load static%}
<link rel="stylesheet" type="text/css" href="{% static 'todoapp/css/bootstrap.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'todoapp/css/bootstrap-reboot.css' %}">
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Title {% endblock title%}</title>
    <style>
        .row{
            margin-top: 10px;
        }
    </style>
</head>
<body>
    <div class="authentication">
        <div class="home"><a href="{% url 'todoapp:index'%}">Home</a></div>
        {% if user.is_authenticated %}
            <a href="{% url 'accounts:logout' %}">Logout</a>
        {% else %}
            <div class="login signup">
                <a href="{% url 'accounts:register' %}">Signup</a>
                <a href="{% url 'accounts:login' %}">Login</a>
            </div>
        {%endif %}
    </div>
    {% block content %}
        Content
    {% endblock content %}
</body>
</html>

todoapp/templates/todoapp/index.html
{% extends 'todoapp/base.html'%}

{% block title%}
    HomePage
{% endblock title%}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col">
            </div>
            <div class="col-6">
                <h2>A To-do task list App</h2>
            </div>
            <div class="col">
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col">

            </div>
            <div class="col-6">
                <h2>List of all tasks to be done</h2>
                {% if task_list %}
                    {% for task in task_list%}
                    <div class="container">
                        <div class="row">
                            <div class="col-md-auto">
                                {{task.task_text}}
                            </div>
                            <div class="col">
                                Time Left {{task.task_deadline|timeuntil}}
                                <form action="{% url 'todoapp:remove_task' task.id%}">
                                    <input class="btn btn-primary" type="submit" value="Done">
                                </form>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                {% endif %}
                <form action="{% url 'todoapp:add_task'%}">
                    <div>
                        <input class="btn btn-primary" type="submit" value="Add new task">
                    </div>
                </form>
            </div>
            <div class="col">

            </div>
        </div>
    </div>
{% endblock content %}